# Generated by Django 3.2.9 on 2022-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctword',
            name='title',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correctword',
            name='points',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
